---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-apps
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: infra-argocd
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy app-of-apps and apps to the infra-argocd namespace
  destinations:
  - namespace: infra-argocd
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: argoproj.io
    kind: Application
  - group: argoproj.io
    kind: AppProject
  sourceRepos:
  - https://github.com/adfinis/sks-vault-demo.git
  - https://charts.adfinis.com
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-argocd
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: infra-argocd
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy the hosted argocd instance
  destinations:
  - namespace: infra-argocd
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://argoproj.github.io/argo-helm
  clusterResourceWhitelist:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-custom-resources
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: infra-custom-resources
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy custom resources
  destinations:
  - namespace: infra-argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  sourceRepos:
  - https://github.com/adfinis/sks-vault-demo.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security-vault
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: security-vault
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy vault to the security-vault namespace
  destinations:
  - namespace: security-vault
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://helm.releases.hashicorp.com
