---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-resources
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: infra-custom-resources
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  destination:
    namespace: infra-argocd
    server: https://kubernetes.default.svc
  project: infra-custom-resources
  syncPolicy:
    automated: {}
  source:
    path: manifests/custom-resources
    repoURL: https://github.com/adfinis/sks-vault-demo.git
    targetRevision: HEAD
